### ISSUE TITLE
Do not use the absolute path to the workspace for the rich presence: rpc.detailsEditing

### ISSUE THREAD

**Issue by HTG-YT** [LeonardSSH/coc-discord-rpc#8]
I only wanted to show the name of my workspace, instead of the entire path to the workspace. Is there a way to configure it like this?

**Comment by HTG-YT** [comment]
I dug further into the source code:

https://github.com/LeonardSSH/coc-discord-rpc/blob/main/src/structures/Activity.ts#L37

I guess it didn't work as in the directories on Windows are actually *backslashes*: `\` instead of the regular slash: `/`. The source only splits on regular slashes but not backslashes.

**Comment by HTG-YT** [comment]
@LeonardSSH any plans to fix this, as in: checking the current platform and split on `\` if it's Windows, and `/` if its not Windows?

**Comment by LeonardSSH** [comment]
It will be fixed in the next version, which will be in about a few days. Due to the fact that the entire extension was rewritten and passed on events, no more timers. 

At the same time, moving to events, we added some new features, including the 'Viewing' option of the file.

![yes](https://cyberpunk.is-a.fail/plQrMF.png)
![no](https://cyberpunk.is-a.fail/dW5o3w.png)

😊

**Comment by HTG-YT** [comment]
Thank you 👍

**Comment by HTG-YT** [comment]
I have updated to version `4.0.0` and it is fixed. Thank you!
